# Generated by Django 5.2.6 on 2025-09-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediater', '0002_adminprofile_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='mediater.buyerprofile'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
