# Generated by Django 5.2.6 on 2025-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediater', '0003_buyerprofile_address_buyerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='feedback',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_id',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
